spring.application.name=ESCProject
spring.datasource.url=jdbc:mysql://localhost:3306/esconnectDB?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
#Melek datasource password root

server.port=8083

### JPA / HIBERNATE ###
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
logging.level.org.hibernate.SQL=warn
logging.level.org.hibernate.orm.jdbc.bind=warn
server.servlet.context-path=/escproject/api

# JWT Configuration
jwt.secret=mySecretKeyForJWTAuthenticationIsVeryLongAndSecureEnoughForHS256Algorithm1234567890
jwt.expiration=86400000
